output "aws_caller_identity_account_id" {
  description = "AWS Account ID"
  value       = data.aws_caller_identity.current.account_id
}

output "aws_caller_identity_user_arn" {
  description = "ARN of the AWS user/role"
  value       = data.aws_caller_identity.current.arn
}

output "ubuntu_ami_id" {
  description = "Ubuntu AMI ID used for the instance"
  value       = data.aws_ami.ubuntu.id
}

output "ubuntu_ami_name" {
  description = "Ubuntu AMI name"
  value       = data.aws_ami.ubuntu.name
}

output "instance_ids" {
  description = "EC2 instance IDs by instance key"
  value = {
    for key, instance in aws_instance.instances : key => instance.id
  }
}

output "instance_arns" {
  description = "EC2 instance ARNs by instance key"
  value = {
    for key, instance in aws_instance.instances : key => instance.arn
  }
}

output "instance_public_ips" {
  description = "Elastic public IP addresses by instance key"
  value = {
    for key, eip in aws_eip.instances : key => eip.public_ip
  }
}

output "instance_elastic_ip_allocation_ids" {
  description = "Elastic IP allocation IDs by instance key"
  value = {
    for key, eip in aws_eip.instances : key => eip.allocation_id
  }
}

output "instance_private_ips" {
  description = "Private IP addresses by instance key"
  value = {
    for key, instance in aws_instance.instances : key => instance.private_ip
  }
}

output "ssh_private_key_path" {
  description = "Local path of the private SSH key generated by Terraform"
  value       = local.ansible_ssh_private_key_file
}

output "ssh_commands" {
  description = "Commands to connect to the EC2 instances over SSH"
  value = {
    for key, eip in aws_eip.instances :
    key => "ssh -i ${local.ansible_ssh_private_key_file} ${var.ansible_ssh_user}@${eip.public_ip}"
  }
}
