# SPDX-License-Identifier: MIT-0
---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_usefull_packages:
  - ca-certificates
  - curl

docker_service_name: docker
docker_project_path: /cloud-1
docker_compose_file: docker-compose.yml
docker_env_file: .env
docker_stack_state: present

docker_apt_source_file: /etc/apt/sources.list.d/docker.sources
docker_apt_uri: https://download.docker.com/linux/ubuntu
docker_apt_components: stable

docker_keyring_dir: /etc/apt/keyrings
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_gpg_dest: /etc/apt/keyrings/docker.asc

docker_users: [
  "{{ user_session }}"
]

docker_mysql_image: mysql:8.0
docker_nginx_image: nginx:1.31.1
docker_wordpress_image: wordpress

docker_volume_directories:
  - "{{ docker_project_path }}/data/wp"
  - "{{ docker_project_path }}/data/db"

docker_volume_directories_wordpress: "{{ docker_project_path }}/data/wp"
docker_volume_directories_database: "{{ docker_project_path }}/data/db"
