output "aws_caller_identity_account_id" {
  description = "AWS Account ID"
  value       = data.aws_caller_identity.current.account_id
}

output "aws_caller_identity_user_arn" {
  description = "ARN of the AWS user/role"
  value       = data.aws_caller_identity.current.arn
}

output "ubuntu_ami_id" {
  description = "Ubuntu AMI ID used for the instance"
  value       = data.aws_ami.ubuntu.id
}

output "ubuntu_ami_name" {
  description = "Ubuntu AMI name"
  value       = data.aws_ami.ubuntu.name
}

output "instance_ids" {
  description = "EC2 instance IDs by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => aws_instance.instances["${group_key}.${instance_key}"].id
    }
  }
}

output "instance_arns" {
  description = "EC2 instance ARNs by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => aws_instance.instances["${group_key}.${instance_key}"].arn
    }
  }
}

output "instance_public_ips" {
  description = "Elastic public IP addresses by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => aws_eip.instances["${group_key}.${instance_key}"].public_ip
    }
  }
}

output "instance_elastic_ip_allocation_ids" {
  description = "Elastic IP allocation IDs by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => aws_eip.instances["${group_key}.${instance_key}"].allocation_id
    }
  }
}

output "instance_private_ips" {
  description = "Private IP addresses by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => aws_instance.instances["${group_key}.${instance_key}"].private_ip
    }
  }
}

output "security_group_ids" {
  description = "Security group IDs by group key"
  value = {
    for group_key, security_group in aws_security_group.instance_groups :
    group_key => security_group.id
  }
}

output "ssh_private_key_path" {
  description = "Local path of the private SSH key generated by Terraform"
  value       = local.ansible_ssh_private_key_file
}

output "ssh_commands" {
  description = "Commands to connect to the EC2 instances over SSH by group and instance key"
  value = {
    for group_key, group in local.instance_groups : group_key => {
      for instance_key, instance in group.instances :
      instance_key => "ssh -i ${local.ansible_ssh_private_key_file} ${var.ansible_ssh_user}@${aws_eip.instances["${group_key}.${instance_key}"].public_ip}"
    }
  }
}
