---
- name: Fetch the Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ docker_keyring_path }}"
    mode: '0644'

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: "{{ dpkg_arch.stdout }}"
    signed_by: "{{ docker_keyring_path }}"

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
