---
- name: Déployer nginx
  hosts: web
  become: true
  tasks:
    - ansible.builtin.apt:
        name: nginx
        state: present
    - ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true